/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_project_dnareader_WorkingWithJni */

#ifndef _Included_ru_project_dnareader_WorkingWithJni
#define _Included_ru_project_dnareader_WorkingWithJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_project_dnareader_WorkingWithJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_project_dnareader_WorkingWithJni_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
