/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_ivan_hellojni4_clas */

#ifndef _Included_ru_project_dnareader_MainActivity
#define _Included_ru_project_dnareader_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_ivan_hellojni4_clas
 * Method:    reader
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_project_dnareader_MainActivity_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
